# Generated by Django 5.1.2 on 2024-10-27 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaestroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_cliente', models.CharField(max_length=11, unique=True)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('direccion_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_cliente', models.EmailField(blank=True, max_length=50, null=True)),
                ('coordinador_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('registro_cliente', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_conductor', models.CharField(max_length=10, unique=True)),
                ('nombre_conductor', models.CharField(max_length=50)),
                ('apellido_conductor', models.CharField(max_length=50)),
                ('celular_conductor', models.CharField(max_length=12)),
                ('brevete_conductor', models.CharField(max_length=10)),
                ('vencimiento_brevete', models.DateField()),
                ('registro_conductor', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_empresa', models.CharField(max_length=11, unique=True)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('direccion_empresa', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_proveedor', models.CharField(max_length=11, unique=True)),
                ('nombre_proveedor', models.CharField(max_length=60)),
                ('direccion_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('celular_proveedor', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_proveedor', models.EmailField(blank=True, max_length=50, null=True)),
                ('coordinador_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('registro_proveedor', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroSerieDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_documento', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroTipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroUbigeo',
            fields=[
                ('ubigeo_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50)),
                ('nombre_provincia', models.CharField(max_length=50)),
                ('nombre_distrito', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaestroMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_movilidad', models.CharField(max_length=10, unique=True)),
                ('anio_movilidad', models.CharField(blank=True, max_length=4, null=True)),
                ('asiento_movilidad', models.CharField(max_length=2)),
                ('soat_personal', models.DateField(blank=True, null=True)),
                ('soat_turistico', models.DateField(blank=True, null=True)),
                ('revision_tecnica', models.DateField()),
                ('revision_turistica', models.DateField(blank=True, null=True)),
                ('poliza_terceros', models.DateField(blank=True, null=True)),
                ('poliza_todo', models.DateField(blank=True, null=True)),
                ('tuce_atu', models.DateField(blank=True, null=True)),
                ('tuce_lima', models.DateField(blank=True, null=True)),
                ('tuce_callao', models.DateField(blank=True, null=True)),
                ('registro_cliente', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.maestromarca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.maestromodelo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.maestroproveedor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.maestrotipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_cliente', models.CharField(max_length=11, unique=True)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura'), ('RECIBO', 'Recibo')], max_length=7)),
                ('contacto_servicio', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_registro_servicio', models.DateTimeField(auto_now_add=True)),
                ('solicitud_servicio', models.DateField()),
                ('pax_servicio', models.IntegerField(blank=True, null=True)),
                ('inicio_servicio', models.DateTimeField(blank=True, null=True)),
                ('final_servicio', models.DateTimeField(blank=True, null=True)),
                ('precio_servicio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('alquiler_servicio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado_detalle', models.BooleanField(default=True)),
                ('recorrido_inicio', models.CharField(blank=True, max_length=120, null=True)),
                ('recorrido_llegada', models.CharField(blank=True, max_length=120, null=True)),
                ('cancelado', models.BooleanField(default=False)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.maestrocliente')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reserva.maestroconductor')),
                ('movilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reserva.maestromovilidad')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.maestroservicio')),
                ('ubigeo_llegada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llegada', to='reserva.maestroubigeo')),
                ('ubigeo_partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partida', to='reserva.maestroubigeo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFinalServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('cobrado_por_conductor', models.BooleanField(default=False)),
                ('fecha_final_servicio', models.DateTimeField(auto_now_add=True)),
                ('detalle_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.detalleservicio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.maestroempresa')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reserva.maestroseriedocumento')),
            ],
        ),
    ]
